# Generated by Django 5.0.3 on 2024-04-02 19:23

from django.db import migrations
from django.conf import settings
import json
from django.contrib.auth import get_user_model
User = get_user_model()

def load_initial_movie_data(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    movies_data_file = settings.BASE_DIR / 'data/movies.json'
    mov_list = []
    with open(movies_data_file) as fp:
        data = fp.read()
        movies = json.loads(data)
        for row in movies:
            rdate = row.pop('release_date')
            mov = Movie(
                **row,
                release_date=rdate
            )
            mov_list.append(mov)
        Movie.objects.bulk_create(mov_list)


def load_initial_ratings_data(apps, schema_editor):
    VisionaryUser = apps.get_model('accounts', 'VisionaryUser')
    Movie = apps.get_model('movies', 'Movie')
    Rating = apps.get_model('movies', 'Rating')
    ratings_data_file = settings.BASE_DIR / 'data/ratings.json'
    with open(ratings_data_file) as fp:
        data = fp.read()
        ratings = json.loads(data)
        for row in ratings:
            user = VisionaryUser.objects.get(id=row['user_id'])
            movie = Movie.objects.get(id=row['movie_id'])
            Rating.objects.create(
                id=row['id'],
                user=user,
                movie=movie,
                rating=float(row['rating'])
            )


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_movie_data),
        migrations.RunPython(load_initial_ratings_data)
    ]
