# Generated by Django 5.0.3 on 2024-04-02 19:23

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password
import json


def load_initial_user_data(apps, schema_editor):
    VisionaryUser = apps.get_model('accounts', 'VisionaryUser')
    users_data_file = settings.BASE_DIR / 'data/users.json'
    with open(users_data_file) as fp:
        data = fp.read()
        users = json.loads(data)
        for row in users:
            password = row.pop('password')
            user = VisionaryUser.objects.create(
                **row,
                password=make_password(password)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_user_data)
    ]
