# Generated by Django 5.0.3 on 2024-04-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240403_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionaryuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Phone number'),
        ),
    ]
